### ISSUE TITLE
Render EML function

### ISSUE THREAD

**Issue by karawoo** [ropenscilabs/emldown#12]
First step: turn the code in `inst/notebook/testing.R` into a function.

Next step: add ability to configure e.g. CSS based on YAML

**Comment by karawoo** [comment]
Basic `render_eml()` function added in dc4670eaf08df54cae1261c29910d40b83473121.

**Comment by maelle** [comment]
Archiving this repository as it has been inactive for a while. https://devguide.ropensci.org/curationpolicy.html#incubator-packages

See also the dataspice package https://docs.ropensci.org/dataspice/
