### ISSUE TITLE
Dataset template

### ISSUE THREAD

**Issue by karawoo** [ropenscilabs/emldown#13]
Create a template that incorporates general information about the dataset (title, abstract, creators, keywords, etc.)

**Comment by karawoo** [comment]
This may be useful for adding the author/creator list: https://stackoverflow.com/a/668850/2921990

**Comment by maelle** [comment]
Archiving this repository as it has been inactive for a while. https://devguide.ropensci.org/curationpolicy.html#incubator-packages

See also the dataspice package https://docs.ropensci.org/dataspice/
