### ISSUE TITLE
dataTable template

### ISSUE THREAD

**Issue by karawoo** [ropenscilabs/emldown#14]
Create a template with information about dataTables. Subcomponents of this include:

 - entityName
 - entityDescription
 - physical
 - attributeList

**Comment by maelle** [comment]
The current table template has all that's mentioned in the list above, but I'm not sure I can close this before someone else tells me it looks ok :grimacing:

**Comment by maelle** [comment]
I might want to find a way to make the table searchable / filterable, a bit like the nice tables one can get in RMarkdown. This way if one is looking for variables with "fuel" in the description, it's easier to find them all.

**Comment by aammd** [comment]
Well, we have already stuffed one html widget into the website -- why not another? I love the `DT` package; can its results be saved in the same way?

**Comment by maelle** [comment]
I'll try to have a look soon at how `DT` works. Until now what I saw with Javascript+CSS+xlst without that package looked complicated and I didn't have time to experiment a lot.

**Comment by maelle** [comment]
Archiving this repository as it has been inactive for a while. https://devguide.ropensci.org/curationpolicy.html#incubator-packages

See also the dataspice package https://docs.ropensci.org/dataspice/
