### ISSUE TITLE
Coverage template

### ISSUE THREAD

**Issue by karawoo** [ropenscilabs/emldown#15]
Coverage includes:

- geographicCoverage
- temporalCoverage
- taxonomicCoverage

**Comment by jhollist** [comment]
Got a start at geographic coverage in #18.  Figured having separate templates for each was preferable for more flexibility for layout of output.  Also my idea was to grab the coords and eventually put them into leaflet (ala #2) directly in the xsl.

**Comment by maelle** [comment]
Archiving this repository as it has been inactive for a while. https://devguide.ropensci.org/curationpolicy.html#incubator-packages

See also the dataspice package https://docs.ropensci.org/dataspice/
