### ISSUE TITLE
option to produce an html "snippet"

### ISSUE THREAD

**Issue by aammd** [ropenscilabs/emldown#17]
Sometimes, instead of building an entire website, authors might want just a partial one. This would come in handy if, for example, you wanted to include the rendered EML website into another, more complete, website. 

This might be done by plugging the essential xslt templates into a simpler, partial ("snippit") HTML file. Then, the function `render_eml()` would apply one or the other, depending on the value of an argument (something like `partial = TRUE`)

**Comment by maelle** [comment]
Archiving this repository as it has been inactive for a while. https://devguide.ropensci.org/curationpolicy.html#incubator-packages

See also the dataspice package https://docs.ropensci.org/dataspice/
