### ISSUE TITLE
consider reuse/modification of existing XSLT

### ISSUE THREAD

**Issue by mbjones** [ropenscilabs/emldown#26]
@maelle @karawoo @aammd @jhollist and others -- I think `emldown` is awesome 🎉:tada: :tada: in the way it aims to create a standalone HTML representation of an EML document.  I hope the work continues!  I've been lurking as you develop the tool, and it seems that work has paused on trying to develop out a more complete XSLT for the complex EML structure.

We have developed an extensive XSLT for transforming EML to HTML, and we reuse that XSLT in multiple places, including our MetacatUI search application, and the Morpho metadata editor, among others.  Have you considered re-using this XSLT to generate the base HTML, and then restyle that using CSS and other transforms that make it look how you would like in emldown?  

At DataONE, we provide a [`view` service](https://releases.dataone.org/online/api-documentation-v2.0.1/apis/MN_APIs.html#MNView.view) that can run a set of XSLT transforms on a document, and produce an HTML document for further processing.  We then add styles to that, and rearrange it with various Javascript DOM manipulations to produce a final product.  So, you can see the result of running our XSLT styes on a document by running the `view` service to produce raw html.  The same styles could definitely be run locally in R to produce inital HTML to be further styled and modified in `emldown`.

Here is an example:

- A raw EML document
https://arcticdata.io/metacat/d1/mn/v2/object/doi%3A10.18739%2FA2556Q

- The unstyled HTML document from our `view` service using the metacatui XSLT (see view source)
https://arcticdata.io/metacat/d1/mn/v2/views/metacatui/doi:10.18739/A2556Q
<img width="1252" alt="eml-html" src="https://user-images.githubusercontent.com/766407/37079075-c77cf56e-218d-11e8-9a6b-fe12b6bb2ad1.png">

- The final styled HTML document after we apply CSS and Javascript
https://arcticdata.io/catalog/#view/doi:10.18739/A2556Q
<img width="1246" alt="eml-rendered" src="https://user-images.githubusercontent.com/766407/37079086-d17d4488-218d-11e8-8697-70a54f299f8d.png">

I see you have a bunch of our XSLT files checked into the emldown repo.  We (@mbjones, @csjx, @mobb, @amoeba, and many others) been developing XSLT for EML for a long time, and would be happy to help consult on how to get past the significant bottleneck of getting the initial EML to HTML conversion working.  Please let us know how we can help.  And thanks for the awesome work!

**Comment by maelle** [comment]
Thanks a ton! I think we're all busy with other things atm but I can say that as soon as I have more time (in a few weeks? months?) I'll definitely digest this into the package, great work and fantastic resource!

**Comment by maelle** [comment]
Archiving this repository as it has been inactive for a while. https://devguide.ropensci.org/curationpolicy.html#incubator-packages

See also the dataspice package https://docs.ropensci.org/dataspice/
