### ISSUE TITLE
Update to use 2.2.0 EML data paper elements

### ISSUE THREAD

**Issue by yvanlebras** [ropenscilabs/emldown#27]
Looking at https://eml.ecoinformatics.org/whats-new-in-eml-2-2-0.html#data-paper-support it seems of interest to add these data papers oriented EML elements to this package isn't it ?

**Comment by maelle** [comment]
Archiving this repository as it has been inactive for a while. https://devguide.ropensci.org/curationpolicy.html#incubator-packages

See also the dataspice package https://docs.ropensci.org/dataspice/
