### ISSUE TITLE
short summary of Thursday work

### ISSUE THREAD

**Issue by aammd** [ropenscilabs/emldown#6]
Write a quick summary of what we accomplished Thursday, share this with @jhollist et al

**Comment by aammd** [comment]
## Thursday Report 😹 😅 ☕️ 

*Project goal* : create some handy functions for reading and visualizing EML documents. 

Our biggest accomplishment today was deciding how to structure the project. We started out using some `.xslt` files which were donated to us by @amoeba , and our goal was to figure out how to reuse these. However, we ran into a few challenges: we needed to learn xslt first, we seemed to be missing some Javascript files that the xslt scripts used, and we found it hard to manipulate the formatting.

Instead, we decided to being more-or-less from "scratch". We copied a basic Bootstrap template into the `/inst` directory, they converted _it_ into an `xlst` template. Now, we are going to work on adding some of the essential EML elements to the website (we probably won't catch them all!). So our goal is the "Minimal Viable Project". We are also thinking about how to add some cool Bootstrap components into the website (a nice navbar, a footer, perhaps some badges, perhaps some icons). 

One cool extra idea is to write an R function which knows how to place some arbitrary HTML into the template. This will let us put more details into the document, perhaps using htmlwidgits (e.g. a leaflet map)

Now that we have a clearer direction, we have a much better idea of how to chop the project up into pieces. So if anyone wants to join our group (here in LA or remotely) it should be easier!

We're off to a strong start! Looking forward to working on this again tomorrow!!

@aammd @cboettig @karawoo @maelle cc @jhollist @nistara

**Comment by jhollist** [comment]
Looks great all!  Happy to help out where I can.  I've been browsing the code and I think I have a general understanding of the direction.

Any thought given to the functions and names?  I could at least get some skeletons set up for you tomorrow morning.  

But now it's time for some :beers:

**Comment by maelle** [comment]
Archiving this repository as it has been inactive for a while. https://devguide.ropensci.org/curationpolicy.html#incubator-packages

See also the dataspice package https://docs.ropensci.org/dataspice/
