### ISSUE TITLE
Use the rdataone package for finding test EML

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/emldown#9]
https://github.com/DataONEorg/rdataone

With a bunch of EML downloaded via that package, stress test `emldown`.

**Comment by amoeba** [comment]
I'm very familiar with this and would be happy to help by either doing this or helping someone else!

**Comment by maelle** [comment]
Archiving this repository as it has been inactive for a while. https://devguide.ropensci.org/curationpolicy.html#incubator-packages

See also the dataspice package https://docs.ropensci.org/dataspice/
